### PR TITLE
fix InfiniteQuery stuck bug

### PR DESCRIPTION
**Pull request by iOSonntag**

### CODE REVIEW

**Comment by iOSonntag** [comment]
I will test this out, give me a few shots

**Comment by iOSonntag** [comment]
Interesting enough it prooves the bug, unfortunatly the call stack is unusable:

image

Let me do real quick one or two more tests, but I think it solves the issue

**Comment by iOSonntag** [comment]
YES its fixed with your proposal, should I create a new PR or do you add this into source?

**Comment by iOSonntag** [comment]
Okay updated this PR to only modify `query_base.dart` - I used `dart format src/query_base.dart` but it said 0 changes, I guess it was alright then.

**Review by D-James-GH — APPROVED** [review]

**Pull request merged**
