### PR TITLE
Supports serialization/deserialization at the Query level

### PR DESCRIPTION
**Pull request by josh-burton**
I've taken a stab at fixing #11.

These changes are breaking changes.

- refactors QueryConfig: splits config into a global `CachedQueryConfig` and query level `QueryConfig`. `QueryConfig` extends from `CachedQueryConfig` and introduces serializer/deserializer fields.
- removes generic types from `StorageInterface`. Storage methods put/get strings. Serializing/Deserializing to/from a string is now the responsibility of the query config.
- if no serializer/deserliazer is specified, jsonEncode/jsonDecode is used.

### CODE REVIEW

**Comment by D-James-GH** [comment]
Hey @josh-burton, I've had a look through and I like the direction of this. I definitely have serialize/deserialize the wrong way around. I also think it's a great idea to allow the user to be able to specify both a serializer and deserializer. 

If we are splitting the config I think a name like `GlobalQueryConfig` or something might be clearer.

Currently, the query config is merged when you create a query. This means that if you only specify `refetchDuration` the rest of the config will use the previously set global config. I could be wrong but I couldn't see this happening in your branch. It may be that I've missed writing a test for this so apologies for that.

The reason for the cached storage having a generic is that not all storage adapters use strings. For example, we use Hive in an older app allowing for the direct storing of a dart object rather than a string. So this might need to be reverted. We may also need an easy way to prevent `jsonEncode` from being called if you are storing objects, although I suppose you could just pass an empty callback.

Finally, was there a reason to update the minimum dart version to 2.17 apart from the super class shorthand?

**Comment by josh-burton** [comment]
Thanks for taking a look and your thorough reply. 

 - I had bumped dart to 2.17 only to use super params but I'll revert this
 - I'll rename the config to Global config and look into whether the query config gets merged with the global config.
 
 Do you have an example of your hive storage adapter and how the generic typing is used? I'm wondering if rather than a deserialize/serialize function call each query should be able to override writing/reading from storage (which would include the deserialize/serialize step).
 
 What are your thoughts?

**Comment by D-James-GH** [comment]
I don't have an example of the hive adapter. But the type parameter is just dynamic so it can handle any object.
>I'm wondering if rather than a deserialize/serialize function call each query should be able to override writing/reading from storage (which would include the deserialize/serialize step).

I'm not sure I understand how this would work or what benefits it would bring. Would there still be a need for the storage package? What would this look like from a users point of view?

**Comment by D-James-GH** [comment]
Implemented some of the suggestions in https://github.com/D-James-GH/cached_query/commit/4aca144dd49589309d49969f9f11ce42eeff87ce
. Credited in the git commit. I didn't merge this straight in as I wanted to keep some of the backward compatibility and this is no longer up to date

**Pull request closed without merging**
